### ISSUE TITLE
Question about calculating the LR statistic

### ISSUE THREAD

**Issue by mishaploid** [psoerensen/qgg#1]
Dear Dr. Sørensen,

I am attempting to use the likelihood ratio statistic from the Edwards et al. 2015 paper, described as: 

>  Likelihood ratios (LR) were calculated as twice the difference between the log-transformed likelihood of the simple model (3) and the full model (1).

Would this be equivalent to the following? 

> 2 x [ln(likelihood for GFBLUP model) - ln(likelihood for GBLUP model)]

Thank you for your time.

Best wishes,
Sarah

**Comment by psoerensen** [comment]
Dear Sarah,

that should be correct. You can also have alook at the following wikipedia page. https://en.wikipedia.org/wiki/Likelihood-ratio_test?

Kind regards

Peter

________________________________

**Comment by mishaploid** [comment]
Thank you!
