### ISSUE TITLE
ncores

### ISSUE THREAD

**Issue by dleopold** [psoerensen/qgg#10]
It appears (for me at least) that the ncores argument does not have the desired effect. I have tries setting ncores > 1 in both grm() and greml() without any effect. Is this feature not yet implemented? or perhaps there is a dependency or setting that must be satisfied?

**Comment by psoerensen** [comment]
Dear David,
there are currently some issues with the ncores argument. This is because I
had to stop using OpenMP which was controlled by the argument ncores. The
reason is that OpenMP is a platform-dependent facility and the builds of R
4.0.0 on macOS are not planned to have it (it is not supported by the
system compiler).,
I am working on a fix for this. Sorry about that!

**Comment by dleopold** [comment]
Thank you for the explanation. The package has been working well for me otherwise. One additional thing I have not been able to figure out is how to calculate a standard error associated with greml estimates of heritability [ie, G/(G+E)]. In the tutorial, I see how cross-validation is used for assessing the stability of the estimate, but the the results are obviously going to be highly influenced by the proportion of sample are held out in each iteration. Is it possible to get a standard error associated the point etimate of heritability from the full model? I could post this question to a new issue but I suspect the issue here may be my own limited knowledge as opposed to any issue with the package.

**Comment by psoerensen** [comment]
Hi Devin, I will add some examples on how to compute standard errors of
heritability. It may take a week or so before I will do this.
(and sorry for calling you David instead of Devin!)

**Comment by dleopold** [comment]
Thanks for working on this. If you do not have time to make a worked example of calculating the standard error, I am happy to try and work through it if you can point me in the right direction.

**Comment by PDRohde** [comment]
Dear Devin,

To compute the standard error of the heritability estimate you need to work out the Taylor series expansions. This is somewhat trivial for simple models when you only have two random effects; G and E, but for more complex models it becomes a bit tricky.

Luckily, the R package car() can do these expansions given estimated parameters and a covariance matrix.

Below is a small example on how you can do this with our package.

`library(qgg);library(car)`
`W <- matrix(rnorm(1000000), ncol = 1000)`
`colnames(W) <- as.character(1:ncol(W))`
`rownames(W) <- as.character(1:nrow(W))`
`y <- rowSums(W[, 1:10]) + rowSums(W[, 501:510]) + rnorm(nrow(W))`

`# Create model`
`data <- data.frame(y = y, mu = 1)`
`fm <- y ~ 0 + mu`
`X <- model.matrix(fm, data = data)`

`# Compute GRM`
`GRM <- grm(W = W)`

`# REML analyses`
`fitG <- greml(y = y, X = X, GRM = list(GRM))`

`# Compute heritability and SE`
`theta <- fitG$theta`
`covar <- fitG$asd`
`rownames(covar)<- colnames(covar) <- names(theta)`
`deltaMethod(theta, "G1/(G1+E)", vcov=covar)`

Note that the rows and columns of `covar` should match the names of `theta`.

If your model contains multiple G's; e.g. `G1` and `G2` you simply just do:
`deltaMethod(theta, "(G1+G2)/(G1+G2+E)", vcov=covar)`

Cheers
Palle
