### ISSUE TITLE
Error in file.exists(bedfiles)

### ISSUE THREAD

**Issue by ShiLiangyu94** [psoerensen/qgg#13]
Dear Dr. Sørensen,

> bedfiles <- system.file("extdata", "sample_chr1.bed", package = "qgg")
> bimfiles <- system.file("extdata", "sample_chr1.bim", package = "qgg")
> famfiles <- system.file("extdata", "sample_chr1.fam", package = "qgg")
> 
> Glist <- gprep(study="Example", bedfiles=bedfiles, bimfiles=bimfiles,
+              famfiles=famfiles)
Finished processing fam file /opt/R/4.0.2/lib/R/library/qgg/extdata/sample_chr1.fam
Finished processing bim file /opt/R/4.0.2/lib/R/library/qgg/extdata/sample_chr1.bim
Finished processing bed file /opt/R/4.0.2/lib/R/library/qgg/extdata/sample_chr1.bed
> W <- getG(Glist=Glist, scale=TRUE, impute=TRUE)
Error in file.exists(bedfiles) : invalid 'file' argument****

**Comment by psoerensen** [comment]
Dear Shi Liang, you need to use the chr argument in the getG function. 
W <- getG(Glist=Glist, scale=TRUE, impute=TRUE, chr=1)
I have updated the function to provide a more informative error message.
Let me know if this fixes your problem.
Peter

**Comment by ShiLiangyu94** [comment]
Thank you very much!
The problem was fixed

**Comment by ShiLiangyu94** [comment]
这是来自QQ邮箱的自动回复邮件。您好，史良玉接受到了您的邮件
