### ISSUE TITLE
Kruskal-Wallis test (KW) for single marker test

### ISSUE THREAD

**Issue by wuqianniandelaok** [psoerensen/qgg#15]
This is a very impressive function for SMT, but I am wondering whether we could use other statistic methods such as KW to analyze?
like:
```
glma <- function(y = NULL, X = NULL, W = NULL, Glist = NULL, chr=NULL,  fit = NULL, verbose=FALSE,
                 statistic = "Kruskal-Wallis", ids = NULL, rsids = NULL, msize = 100, scale = TRUE)
```

**Comment by psoerensen** [comment]
I have not considered that so far, but it might be possible to add this.
Could you point me to a suitable reference describing the statistical
method/test you would like to use?
