### ISSUE TITLE
How to calculate the permanent environmental effect

### ISSUE THREAD

**Issue by ShiLiangyu94** [psoerensen/qgg#16]
Dear Dr. Sørensen,
     How to calculate the permanent environmental effect， when I use DHI data?

**Comment by psoerensen** [comment]
Dear Shiliang, I am not sure I understand your question. Could you please clarify your question?

**Comment by ShiLiangyu94** [comment]
这是来自QQ邮箱的自动回复邮件。您好，史良玉接受到了您的邮件

**Comment by psoerensen** [comment]
Does not help :)

**Comment by ShiLiangyu94** [comment]
Dear Dr. Sørensen,
If I have a model, like this:
Y=Xb+Za+Wpe+e,
Where pe is a vector of  permanent environmental effects,
How should I prepare the data format？ How should I write the model in the program？
