### ISSUE TITLE
Low predictive accuracy compared to GAPIT

### ISSUE THREAD

**Issue by mishaploid** [psoerensen/qgg#2]
Dear Peter,

I am working on a project to identify metabolic pathways that contribute to variation for amino acid composition in seeds of _Arabidopsis thaliana_. GFBLUP is an excellent model for our study, but when I run standard GBLUP in the qgg package I get much lower predictive accuracies compared to results from GAPIT. I am still fairly new to genomic prediction so one thought is that I may be specifying the genotype matrix (W) and/or model incorrectly. Do you have any advice regarding how to specify the inputs and models for the gfm function? 

A basic summary of the code I'm using is below and I am happy to provide more detail or a reproducible example if that would be helpful. The phenotypes are BLUPs corrected for environmental variation.

To generate W: 
`Glist <- prepG(bedfiles="./data/GS_subset/plinkGeneOmeSubset.bed",
               bimfiles="./data/GS_subset/plinkGeneOmeSubset.bim",
               famfiles="./data/GS_subset/plinkGeneOmeSubset.fam", study="AA-gfblup",
               fnRAW="./data/GS_subset/plinkGeneOmeSubset.out")`

`rsids <- unlist(Glist$rsids)`

`W <- getW(Glist, rsids = rsids)`

To run the GBLUP model:
`fm <- paste0(pheno, "~ 1")`
`fm <- as.formula(fm)`
`print(fm)`

parameters for REML analyses and cross validation:
`n <- nrow(W)`
`fold <- 10`
`nsets <- 1000`

`validate <- replicate(nsets, sample(1:n, as.integer(n / fold))) # matrix input`

`fitGB <- gfm(fm = fm, W = W, data = input_data, validate = validate, mkplots = FALSE)`

Thank you for your time.

Best,
Sarah

**Comment by psoerensen** [comment]
?Hi Sarah,

I will prepare an example script to illustrate the use of these new features.

Kind regards

Peter


________________________________

**Comment by mishaploid** [comment]
That would be great, thank you!
