### ISSUE TITLE
Error in read.dcf(path):

### ISSUE THREAD

**Issue by camult** [psoerensen/qgg#3]
When I tried to install it I got the following error:

library("devtools")
install_github("psoerensen/qgg")
Error in read.dcf(path) : 
  Found continuation line starting '                  ro ...' at begin of record.

**Comment by psoerensen** [comment]
?Hi Fernando, we will look into this. Peter

________________________________

**Comment by psoerensen** [comment]
I assume you are using an Windows R version- correct?
At least we found similar issues on Windows R versions.
We are not sure why this happens and it appears the install_github("psoerensen/qgg") installation procedure works on Microsoft R Windows versions.

To avoid this issue we suggest the following installations procedure on Windows R versions:

library(remotes)
install_url(url="https://github.com/psoerensen/qgg/archive/master.zip", INSTALL_opt= "--no-multiarch")

Hopefully this solves the problem!

**Comment by camult** [comment]
It worked, thanks.

**Comment by camult** [comment]
BTW, the function "gprep" is not reading the correct  ".fam" file.
It is written fam <- fread(input=**bimfiles**[1], header=FALSE, data.table = FALSE), but should be famfiles[1] instead.

**Comment by psoerensen** [comment]
fixed - thank you for identifying this bug
